#!/bin/bash
#
# This shellscript builds two small applications: The Lix server daemon,
# and my throwaway test application that simulates a client logging onto
# a server running on localhost.

dubDir="${HOME}/.dub/packages/"
enetDir="$(find ${dubDir} -name derelict-enet-*)/derelict-enet"
utilDir="$(find ${dubDir} -name derelict-util-*)/derelict-util"

commonSrc="ac.d enetglob.d packetid.d permu.d phyu.d repdata.d structs.d style.d version.d"

commonFlags="-I${enetDir}/source -I${utilDir}/source -L-L${enetDir}/lib -L-L${utilDir}/lib -L-lDerelictENet -L-lDerelictUtil"

dmd "./server/"*.d ${commonSrc} -version=lixDaemon ${commonFlags}
dmd "cli-test.d" "client.d" "iclient.d" ${commonSrc} -version=lixClientTester ${commonFlags}
rm "daemon.o"
rm "cli-test.o"
